#
# main にマージされたら、自動で PR を作成し develop にもマージする
#
name: Merge main into develop
on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - "**"
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.1.2
    steps:
      - name: show ruby version
        run: ruby -v
